/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billiard_asik;

/**
 *
 * @author Lenovo
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public AdminForm() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "No HP", "Meja", "Tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jButton1.setText("Print Invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();

        if(baris == -1){

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Pilih data terlebih dahulu!"
            );

            return;
        }

        String invoice =
                "===== INVOICE RESERVASI =====\n\n"
                + "ID : "
                + jTable1.getValueAt(baris, 0)
                + "\nNama : "
                + jTable1.getValueAt(baris, 1)
                + "\nNo HP : "
                + jTable1.getValueAt(baris, 2)
                + "\nMeja : "
                + jTable1.getValueAt(baris, 3);

        javax.swing.JOptionPane.showMessageDialog(
                this,
                invoice
        );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {

            int baris =
                    jTable1.getSelectedRow();

            if(baris == -1){

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Pilih data terlebih dahulu"
                );

                return;
            }

            int id =
                    Integer.parseInt(
                            jTable1.getValueAt(
                                    baris,
                                    0
                            ).toString()
                    );

            java.sql.Connection conn =
                    Koneksi.getConnection();

            String sql =
                    "DELETE FROM reservasi "
                    + "WHERE id=?";

            java.sql.PreparedStatement ps =
                    conn.prepareStatement(sql);

            ps.setInt(
                    1,
                    id
            );

            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Data Berhasil Dihapus"
            );

            tampilData();

        } catch(Exception e){

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {

            int baris =
                    jTable1.getSelectedRow();

            if(baris == -1){

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Pilih data terlebih dahulu"
                );

                return;
            }

            int id =
                    Integer.parseInt(
                            jTable1.getValueAt(
                                    baris,
                                    0
                            ).toString()
                    );

            String namaLama =
                    jTable1.getValueAt(
                            baris,
                            1
                    ).toString();

            String hpLama =
                    jTable1.getValueAt(
                            baris,
                            2
                    ).toString();

            String mejaLama =
                    jTable1.getValueAt(
                            baris,
                            3
                    ).toString();

            String namaBaru =
                    javax.swing.JOptionPane.showInputDialog(
                            this,
                            "Edit Nama",
                            namaLama
                    );

            if(namaBaru == null){
                return;
            }

            String hpBaru =
                    javax.swing.JOptionPane.showInputDialog(
                            this,
                            "Edit No HP",
                            hpLama
                    );

            if(hpBaru == null){
                return;
            }

            String mejaBaru =
                    javax.swing.JOptionPane.showInputDialog(
                            this,
                            "Edit Meja",
                            mejaLama
                    );

            if(mejaBaru == null){
                return;
            }

            java.sql.Connection conn =
                    Koneksi.getConnection();

            String sql =
                    "UPDATE reservasi "
                    + "SET nama=?, "
                    + "no_hp=?, "
                    + "meja=? "
                    + "WHERE id=?";

            java.sql.PreparedStatement ps =
                    conn.prepareStatement(sql);

            ps.setString(1, namaBaru);
            ps.setString(2, hpBaru);
            ps.setString(3, mejaBaru);
            ps.setInt(4, id);

            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Data Berhasil Diubah"
            );

            tampilData();

        } catch(Exception e){

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    e.getMessage()
            );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void tampilData() {
      try {

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel)
                jTable1.getModel();

        model.setRowCount(0);

        java.sql.Connection conn =
                Koneksi.getConnection();

        java.sql.Statement st =
                conn.createStatement();

        java.sql.ResultSet rs =
                st.executeQuery(
                        "SELECT * FROM reservasi"
                );

        while(rs.next()) {

            Object[] row = {

                rs.getInt("id"),
                rs.getString("nama"),
                rs.getString("no_hp"),
                rs.getString("meja"),
                rs.getDate("tanggal")

            };

            model.addRow(row);
        }

    } catch(Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
    }
}
